### PR TITLE
Improve neovim performance by using nvim_buf_set_lines.

### PR DESCRIPTION
**Pull request by kristijanhusak**
This PR vastly improves performance of commenting/uncommenting a bunch of lines (> 1k) in Neovim.

For example, in js files, which syntax is a bit slow, numbers are these for ~1k lines:

Before: 16.001451 sec
After: 0.030560 sec

I'm assuming this is also slow in Vim (haven't tried), but there's no way to improve it there as far as I know.

Edit: It turns out in Vim it works fine, it's just neovim. 
Edit2: Barebones Vim and Neovim behaves nearly the same, so I guess some other plugins interfere with this. Never the less, this improves performance a lot, and doesn't change any functionality for Vim users.

### CODE REVIEW

**Comment by kristijanhusak** [comment]
`set foldmethod=syntax` is causing the slowness, in case anyone comes across this issue.

**Comment by chrisbra** [comment]
See also my patch here: https://github.com/tpope/vim-commentary/issues/110#issuecomment-511793483

**Comment by kristijanhusak** [comment]
@chrisbra yeah that would solve it for both vim and neovim. Any plans to set up a PR for that?

**Comment by chrisbra** [comment]
well, development here is kind of slow, considering that there are many PRs here. I noticed the problem and did not mind setting up a complete PR, because the change was just so tiny and I wasn't sure whether a PR would actually help here.

**Pull request closed without merging**
